### ISSUE TITLE
Add the traefik to the VelaUX addon and provide dynamic proxy capability for system service 

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/catalog#334]
Currently, we use the Nginx to proxy the API and dex services, it must static configuration. We will integrate more system service that has access endpoint, the static configuration is painful.

Traefik is a modern and cloud-native proxy server, that has dynamic configuration capability, at the same time it is lightweight and easy to use.

**Comment by wonderflow** [comment]
done
