### ISSUE TITLE
[FluxCD Addon]Version and Values fields in Helm should be optional

### ISSUE THREAD

**Issue by chengleqi** [kubevela/catalog#485]
Hi guys, the `Version` and `Values` should be optional IMO.

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/53958238/193513535-5c852fed-1d50-4e6b-ad9e-8da0a6a748cd.png">
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/53958238/193513597-c356730b-7409-47ff-b21d-2d9eacd81ef5.png">

See also:
[FluxCD HelmRelease Version](https://github.com/fluxcd/helm-controller/blob/0fc4d0f1c09bf7ab7c5990aefe480ca4648eeedd/api/v2beta1/helmrelease_types.go#L253) and [FluxCD HelmRelease Values](https://github.com/fluxcd/helm-controller/blob/0fc4d0f1c09bf7ab7c5990aefe480ca4648eeedd/api/v2beta1/helmrelease_types.go#L166)

**Comment by wonderflow** [comment]
ref to https://github.com/kubevela/catalog/pull/481
