### ISSUE TITLE
[FluxCD Addon]Set Default value in GitRepository branch option.

### ISSUE THREAD

**Issue by chengleqi** [kubevela/catalog#486]
This Branch field needs a default value `master` IMO.

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/53958238/193514298-69c68a4b-2bf8-4764-9ced-e350adbdff85.png">

**Comment by wonderflow** [comment]
ref to https://github.com/kubevela/catalog/pull/481

**Comment by FogDong** [comment]
You can add ui schema to avoid this: https://github.com/kubevela/catalog/tree/master/addons/fluxcd/schemas

**Comment by wonderflow** [comment]
follow this PR https://github.com/kubevela/catalog/pull/490/files
