### ISSUE TITLE
[FluxCD Addon]Cannot see Resource Graph in Kustomization

### ISSUE THREAD

**Issue by chengleqi** [kubevela/catalog#487]
I have a Deployment resource and a Service resource in my `Kustomization` App But VelaUX didn't show these resource.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/53958238/193527334-8a455176-250c-4208-a689-6ce7da6189d4.png">

**Expect**
show all the resources like `HelmRelease` in the Resource Graph like below:
<img width="979" alt="image" src="https://user-images.githubusercontent.com/53958238/193527833-ec6fa18c-ce7f-474e-a5b4-7c0fac82fb7f.png">

**Comment by wangyikewxgm** [comment]
The reason is there is a built-in topology-rule of helmRelease and it's sub-resources. Are you interested in contributing to solve this issue  by adding a topology-rule for kutomize. Here are some related docs: https://kubevela.net/docs/platform-engineers/addon/addon-cue#auxiliary-resources , https://kubevela.net/docs/reference/topology-rule.

**Comment by chengleqi** [comment]
Thanks. I'd like to tackle this one.
/assign

**Comment by chengleqi** [comment]
I see. The HelmRelease type resource are built-in [velaql](https://github.com/kubevela/kubevela/blob/fb45a94bb8ec04691f2fdcb79a3a5c46eac832c1/pkg/velaql/providers/query/tree.go#L124) .
I'd better put the kustomize rule in configmap and let vela [merge](https://github.com/kubevela/kubevela/blob/fb45a94bb8ec04691f2fdcb79a3a5c46eac832c1/pkg/velaql/providers/query/collector.go#L139) it.

**Comment by chengleqi** [comment]
Hi guys. I found this can only be implemented by built-in velaql way like HelmRelease.

velaql can list all the resource the HelmRelease has because of the [helmRelease2AnyListOption func](https://github.com/kubevela/kubevela/blob/fb45a94bb8ec04691f2fdcb79a3a5c46eac832c1/pkg/velaql/providers/query/tree.go#L293) but we cannot pass function or pass **dynamic** relevant labels through configmap. And a Deployment doesn't have OwnerReferences with its Kustomization so it also cannot be listed through [GetOwnerReferences](https://github.com/kubevela/kubevela/blob/fb45a94bb8ec04691f2fdcb79a3a5c46eac832c1/pkg/velaql/providers/query/tree.go#L753) when the ListOption func is missed.
