### ISSUE TITLE
[Addon] Add EnvoyProxy Gateway as an experimental addon

### ISSUE THREAD

**Issue by Xunzhuo** [kubevela/catalog#587]
[Envoy Gateway](https://github.com/envoyproxy/gateway) manages Envoy Proxy as a standalone or Kubernetes-based application gateway.

**Comment by Xunzhuo** [comment]
Currently EG does not add support to helm chart, but provided yaml to install. In this case, how can I add it as an addon?

cc @wonderflow : )

**Comment by wonderflow** [comment]
@Xunzhuo Good job, I already find your pull request. Helm chart is not necessary, KubeVela support various kinds of artifacts.

**Comment by Xunzhuo** [comment]
Thank you! @wonderflow I am figuring out how a extension is embedding and running in vela, and the behaviors behind `vela addon enable`.

Any source codes explanations?

I have a quick view and find that vela converts the extensions into Application CR, and add yamls to k8s-objects.

**Comment by wonderflow** [comment]
Yes, addon will be converted into Application CR and run. The main function is here: https://github.com/kubevela/kubevela/blob/master/pkg/addon/addon.go#L911
