### ISSUE TITLE
The catalog repo need refactoring and make things work

### ISSUE THREAD

**Issue by resouer** [kubevela/catalog#59]
The contents in catalog are contributed and maintained by the community so they are generally not guaranteed or supported by OAM/KubeVela maintainers. But, they **should** still work with OAM based app platform.

The refactoring needed IMO:

0. Remove/deprecate unneeded traits/workloads which overlap with KubeVela.
1. Use KubeVela which is end user facing as the example, rather than OAM runtime which is a lower level component.
2. Align them with requirement of latest OAM runtime release.
3. New directory layout: 
    ```console
    my-cool-trait
      |- README # must have, use KubeVela as example
      |- trait-definition.yaml # must have
      |- my-cool-trait-code # optional
    ```

I believe @wonderflow also have some idea about how to make `oam-dev/catalog` become the first class capability center of KubeVela, assigned.

**Comment by wonderflow** [comment]
Sure, I'm totally agree with this refactor, will do that after the glue code between Definition CUE template and `APPFILE` in kubevela ready.
