### ISSUE TITLE
Release VelaUX v1.9.0

### ISSUE THREAD

**Issue by erkanzileli** [kubevela/catalog#702]
Hi there ✋ 

VelaUX `v1.9.0` is released [here](https://github.com/kubevela/velaux/releases/tag/v1.9.0) but the addon is still using `v1.8.1` as specified [here](https://github.com/kubevela/catalog/blob/master/addons/velaux/metadata.yaml#LL2C16-L2C16).

Can you upgrade the addon too?

**Comment by chivalryq** [comment]
There's something wrong in v1.9.0 release in VelaUX due to migration. I'm fixing it and will release v1.9.1 later. Then the addon will be upgraded.

**Comment by chivalryq** [comment]
VelaUX v1.9.1 is released. Due to the migration. New registry is at: https://kubevela.github.io/catalog/official
```shell
vela addon registry update KubeVela --type helm --endpoint=https://kubevela.github.io/catalog/official
```
