### ISSUE TITLE
The new addon endpoint is not useable

### ISSUE THREAD

**Issue by iambocai** [kubevela/catalog#712]
## Description

In the doc, we can see:
![image](https://github.com/kubevela/catalog/assets/2259715/b43d1418-3b7c-45dd-a41f-0992623caa19)

but when I add/update it as the doc say, it returns follow error:

![image](https://github.com/kubevela/catalog/assets/2259715/3c25bdbb-a642-4b05-824f-549fa289b00e)

and when I visit the url via web browser, it redirect to 404 page too.

![image](https://github.com/kubevela/catalog/assets/2259715/aa36d851-2afb-48c1-9bbb-263799e3a8f8)

it seems the new addon endpoint is not ready yet?

## Envirment

KubeVela 1.8.0

**Comment by wonderflow** [comment]
@iambocai You need to upgrade the vela CLI to 1.9.2+, you can keep using vela-core 1.8.0 if you need.

**Comment by wonderflow** [comment]
The page exists: https://kubevela.io/catalog/official/index.yaml

**Comment by iambocai** [comment]
> doc say, it returns follow error:



> @iambocai You need to upgrade the vela CLI to 1.9.2+, you can keep using vela-core 1.8.0 if you need.

oh i see...  thank you for your reply ~
